/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hephaestus' at '5/31/19 1:13 PM' with Gradle 2.10
 *
 * @author hephaestus, @date 5/31/19 1:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
